name: Deploy documentation

on:
  push:
    branches: ["master"]
    paths:
      - '**.nix'
      - 'docs/*'

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix-build ./docs
        name: build static documentation
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v2
        with:
          path: './result'
      - uses: actions/deploy-pages@v4
        id: deployment
