name: Smoke test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build example configuration
        run: nix build ./examples/flake-maximal --no-write-lock-file
