name: Update module sources
on:
  schedule:
    # every day at 00:00
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  update-sources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Nix 
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update Module Sources
        run: |
          nix-shell ./shell.nix --run ./scripts/update-sources.sh
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "chore: update module sources" || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update module sources
          branch: chore/update-module-sources
          body: |
            Update module sources
